[package]
name = "caskeda-common-package"
version = "0.1.0"
authors = ["Longor1996 <lalongok@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
